// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/address.proto

package org.example.protobuf.models.common;

public final class AddressOuterClass {
  private AddressOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_Address_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_Address_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024common/address.proto\022\006common\"\'\n\007Addres" +
      "s\022\016\n\006street\030\001 \001(\t\022\014\n\004city\030\002 \001(\tB&\n\"org.e" +
      "xample.protobuf.models.commonP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_common_Address_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_common_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_Address_descriptor,
        new java.lang.String[] { "Street", "City", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
