// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/address.proto

package org.example.protobuf.models.common;

public interface AddressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.Address)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string street = 1;</code>
   * @return The street.
   */
  java.lang.String getStreet();
  /**
   * <code>string street = 1;</code>
   * @return The bytes for street.
   */
  com.google.protobuf.ByteString
      getStreetBytes();

  /**
   * <code>string city = 2;</code>
   * @return The city.
   */
  java.lang.String getCity();
  /**
   * <code>string city = 2;</code>
   * @return The bytes for city.
   */
  com.google.protobuf.ByteString
      getCityBytes();
}
