// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/car.proto

package org.example.protobuf.models.common;

public interface CarOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.Car)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string brand = 1;</code>
   * @return The brand.
   */
  java.lang.String getBrand();
  /**
   * <code>string brand = 1;</code>
   * @return The bytes for brand.
   */
  com.google.protobuf.ByteString
      getBrandBytes();

  /**
   * <code>string model = 2;</code>
   * @return The model.
   */
  java.lang.String getModel();
  /**
   * <code>string model = 2;</code>
   * @return The bytes for model.
   */
  com.google.protobuf.ByteString
      getModelBytes();

  /**
   * <code>.common.BodyType body_type = 3;</code>
   * @return The enum numeric value on the wire for bodyType.
   */
  int getBodyTypeValue();
  /**
   * <code>.common.BodyType body_type = 3;</code>
   * @return The bodyType.
   */
  org.example.protobuf.models.common.BodyType getBodyType();
}
