// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/credentials.proto

package org.example.protobuf.models.common;

public interface CredentialsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.Credentials)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.common.EmailCredentials emailMode = 1;</code>
   * @return Whether the emailMode field is set.
   */
  boolean hasEmailMode();
  /**
   * <code>.common.EmailCredentials emailMode = 1;</code>
   * @return The emailMode.
   */
  org.example.protobuf.models.common.EmailCredentials getEmailMode();
  /**
   * <code>.common.EmailCredentials emailMode = 1;</code>
   */
  org.example.protobuf.models.common.EmailCredentialsOrBuilder getEmailModeOrBuilder();

  /**
   * <code>.common.PhoneOtp phoneMode = 2;</code>
   * @return Whether the phoneMode field is set.
   */
  boolean hasPhoneMode();
  /**
   * <code>.common.PhoneOtp phoneMode = 2;</code>
   * @return The phoneMode.
   */
  org.example.protobuf.models.common.PhoneOtp getPhoneMode();
  /**
   * <code>.common.PhoneOtp phoneMode = 2;</code>
   */
  org.example.protobuf.models.common.PhoneOtpOrBuilder getPhoneModeOrBuilder();

  public org.example.protobuf.models.common.Credentials.ModeCase getModeCase();
}
