// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/credentials.proto

package org.example.protobuf.models.common;

public final class CredentialsOuterClass {
  private CredentialsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_EmailCredentials_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_EmailCredentials_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_PhoneOtp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_PhoneOtp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_Credentials_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_Credentials_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030common/credentials.proto\022\006common\"3\n\020Em" +
      "ailCredentials\022\r\n\005email\030\001 \001(\t\022\020\n\010passwor" +
      "d\030\002 \001(\t\".\n\010PhoneOtp\022\024\n\014phone_number\030\001 \001(" +
      "\t\022\014\n\004code\030\002 \001(\t\"k\n\013Credentials\022-\n\temailM" +
      "ode\030\001 \001(\0132\030.common.EmailCredentialsH\000\022%\n" +
      "\tphoneMode\030\002 \001(\0132\020.common.PhoneOtpH\000B\006\n\004" +
      "modeB&\n\"org.example.protobuf.models.comm" +
      "onP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_common_EmailCredentials_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_common_EmailCredentials_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_EmailCredentials_descriptor,
        new java.lang.String[] { "Email", "Password", });
    internal_static_common_PhoneOtp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_common_PhoneOtp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_PhoneOtp_descriptor,
        new java.lang.String[] { "PhoneNumber", "Code", });
    internal_static_common_Credentials_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_common_Credentials_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_Credentials_descriptor,
        new java.lang.String[] { "EmailMode", "PhoneMode", "Mode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
