// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/credentials.proto

package org.example.protobuf.models.common;

public interface PhoneOtpOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.PhoneOtp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string phone_number = 1;</code>
   * @return The phoneNumber.
   */
  java.lang.String getPhoneNumber();
  /**
   * <code>string phone_number = 1;</code>
   * @return The bytes for phoneNumber.
   */
  com.google.protobuf.ByteString
      getPhoneNumberBytes();

  /**
   * <code>string code = 2;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string code = 2;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();
}
