// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package org.example.protobuf.models.person;

/**
 * Protobuf type {@code Person}
 */
public final class Person extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Person)
    PersonOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Person.newBuilder() to construct.
  private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Person() {
    name_ = "";
    car_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Person();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.protobuf.models.person.PersonOuterClass.internal_static_Person_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.protobuf.models.person.PersonOuterClass.internal_static_Person_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.protobuf.models.person.Person.class, org.example.protobuf.models.person.Person.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDRESS_FIELD_NUMBER = 3;
  private org.example.protobuf.models.common.Address address_;
  /**
   * <code>.common.Address address = 3;</code>
   * @return Whether the address field is set.
   */
  @java.lang.Override
  public boolean hasAddress() {
    return address_ != null;
  }
  /**
   * <code>.common.Address address = 3;</code>
   * @return The address.
   */
  @java.lang.Override
  public org.example.protobuf.models.common.Address getAddress() {
    return address_ == null ? org.example.protobuf.models.common.Address.getDefaultInstance() : address_;
  }
  /**
   * <code>.common.Address address = 3;</code>
   */
  @java.lang.Override
  public org.example.protobuf.models.common.AddressOrBuilder getAddressOrBuilder() {
    return getAddress();
  }

  public static final int CAR_FIELD_NUMBER = 4;
  private java.util.List<org.example.protobuf.models.common.Car> car_;
  /**
   * <code>repeated .common.Car car = 4;</code>
   */
  @java.lang.Override
  public java.util.List<org.example.protobuf.models.common.Car> getCarList() {
    return car_;
  }
  /**
   * <code>repeated .common.Car car = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.example.protobuf.models.common.CarOrBuilder> 
      getCarOrBuilderList() {
    return car_;
  }
  /**
   * <code>repeated .common.Car car = 4;</code>
   */
  @java.lang.Override
  public int getCarCount() {
    return car_.size();
  }
  /**
   * <code>repeated .common.Car car = 4;</code>
   */
  @java.lang.Override
  public org.example.protobuf.models.common.Car getCar(int index) {
    return car_.get(index);
  }
  /**
   * <code>repeated .common.Car car = 4;</code>
   */
  @java.lang.Override
  public org.example.protobuf.models.common.CarOrBuilder getCarOrBuilder(
      int index) {
    return car_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (address_ != null) {
      output.writeMessage(3, getAddress());
    }
    for (int i = 0; i < car_.size(); i++) {
      output.writeMessage(4, car_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (address_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getAddress());
    }
    for (int i = 0; i < car_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, car_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.protobuf.models.person.Person)) {
      return super.equals(obj);
    }
    org.example.protobuf.models.person.Person other = (org.example.protobuf.models.person.Person) obj;

    if (getId()
        != other.getId()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (hasAddress() != other.hasAddress()) return false;
    if (hasAddress()) {
      if (!getAddress()
          .equals(other.getAddress())) return false;
    }
    if (!getCarList()
        .equals(other.getCarList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (hasAddress()) {
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
    }
    if (getCarCount() > 0) {
      hash = (37 * hash) + CAR_FIELD_NUMBER;
      hash = (53 * hash) + getCarList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.protobuf.models.person.Person parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.protobuf.models.person.Person parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.protobuf.models.person.Person parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.protobuf.models.person.Person parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.protobuf.models.person.Person parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.protobuf.models.person.Person parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.protobuf.models.person.Person parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.protobuf.models.person.Person parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.protobuf.models.person.Person parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.example.protobuf.models.person.Person parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.protobuf.models.person.Person parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.protobuf.models.person.Person parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.protobuf.models.person.Person prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Person}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Person)
      org.example.protobuf.models.person.PersonOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.protobuf.models.person.PersonOuterClass.internal_static_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.protobuf.models.person.PersonOuterClass.internal_static_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.protobuf.models.person.Person.class, org.example.protobuf.models.person.Person.Builder.class);
    }

    // Construct using org.example.protobuf.models.person.Person.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      name_ = "";

      if (addressBuilder_ == null) {
        address_ = null;
      } else {
        address_ = null;
        addressBuilder_ = null;
      }
      if (carBuilder_ == null) {
        car_ = java.util.Collections.emptyList();
      } else {
        car_ = null;
        carBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.protobuf.models.person.PersonOuterClass.internal_static_Person_descriptor;
    }

    @java.lang.Override
    public org.example.protobuf.models.person.Person getDefaultInstanceForType() {
      return org.example.protobuf.models.person.Person.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.protobuf.models.person.Person build() {
      org.example.protobuf.models.person.Person result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.protobuf.models.person.Person buildPartial() {
      org.example.protobuf.models.person.Person result = new org.example.protobuf.models.person.Person(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.name_ = name_;
      if (addressBuilder_ == null) {
        result.address_ = address_;
      } else {
        result.address_ = addressBuilder_.build();
      }
      if (carBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          car_ = java.util.Collections.unmodifiableList(car_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.car_ = car_;
      } else {
        result.car_ = carBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.protobuf.models.person.Person) {
        return mergeFrom((org.example.protobuf.models.person.Person)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.protobuf.models.person.Person other) {
      if (other == org.example.protobuf.models.person.Person.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.hasAddress()) {
        mergeAddress(other.getAddress());
      }
      if (carBuilder_ == null) {
        if (!other.car_.isEmpty()) {
          if (car_.isEmpty()) {
            car_ = other.car_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCarIsMutable();
            car_.addAll(other.car_);
          }
          onChanged();
        }
      } else {
        if (!other.car_.isEmpty()) {
          if (carBuilder_.isEmpty()) {
            carBuilder_.dispose();
            carBuilder_ = null;
            car_ = other.car_;
            bitField0_ = (bitField0_ & ~0x00000001);
            carBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCarFieldBuilder() : null;
          } else {
            carBuilder_.addAllMessages(other.car_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readInt64();

              break;
            } // case 8
            case 18: {
              name_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getAddressFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 26
            case 34: {
              org.example.protobuf.models.common.Car m =
                  input.readMessage(
                      org.example.protobuf.models.common.Car.parser(),
                      extensionRegistry);
              if (carBuilder_ == null) {
                ensureCarIsMutable();
                car_.add(m);
              } else {
                carBuilder_.addMessage(m);
              }
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private org.example.protobuf.models.common.Address address_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.example.protobuf.models.common.Address, org.example.protobuf.models.common.Address.Builder, org.example.protobuf.models.common.AddressOrBuilder> addressBuilder_;
    /**
     * <code>.common.Address address = 3;</code>
     * @return Whether the address field is set.
     */
    public boolean hasAddress() {
      return addressBuilder_ != null || address_ != null;
    }
    /**
     * <code>.common.Address address = 3;</code>
     * @return The address.
     */
    public org.example.protobuf.models.common.Address getAddress() {
      if (addressBuilder_ == null) {
        return address_ == null ? org.example.protobuf.models.common.Address.getDefaultInstance() : address_;
      } else {
        return addressBuilder_.getMessage();
      }
    }
    /**
     * <code>.common.Address address = 3;</code>
     */
    public Builder setAddress(org.example.protobuf.models.common.Address value) {
      if (addressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        address_ = value;
        onChanged();
      } else {
        addressBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.common.Address address = 3;</code>
     */
    public Builder setAddress(
        org.example.protobuf.models.common.Address.Builder builderForValue) {
      if (addressBuilder_ == null) {
        address_ = builderForValue.build();
        onChanged();
      } else {
        addressBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.common.Address address = 3;</code>
     */
    public Builder mergeAddress(org.example.protobuf.models.common.Address value) {
      if (addressBuilder_ == null) {
        if (address_ != null) {
          address_ =
            org.example.protobuf.models.common.Address.newBuilder(address_).mergeFrom(value).buildPartial();
        } else {
          address_ = value;
        }
        onChanged();
      } else {
        addressBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.common.Address address = 3;</code>
     */
    public Builder clearAddress() {
      if (addressBuilder_ == null) {
        address_ = null;
        onChanged();
      } else {
        address_ = null;
        addressBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.common.Address address = 3;</code>
     */
    public org.example.protobuf.models.common.Address.Builder getAddressBuilder() {
      
      onChanged();
      return getAddressFieldBuilder().getBuilder();
    }
    /**
     * <code>.common.Address address = 3;</code>
     */
    public org.example.protobuf.models.common.AddressOrBuilder getAddressOrBuilder() {
      if (addressBuilder_ != null) {
        return addressBuilder_.getMessageOrBuilder();
      } else {
        return address_ == null ?
            org.example.protobuf.models.common.Address.getDefaultInstance() : address_;
      }
    }
    /**
     * <code>.common.Address address = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.example.protobuf.models.common.Address, org.example.protobuf.models.common.Address.Builder, org.example.protobuf.models.common.AddressOrBuilder> 
        getAddressFieldBuilder() {
      if (addressBuilder_ == null) {
        addressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.example.protobuf.models.common.Address, org.example.protobuf.models.common.Address.Builder, org.example.protobuf.models.common.AddressOrBuilder>(
                getAddress(),
                getParentForChildren(),
                isClean());
        address_ = null;
      }
      return addressBuilder_;
    }

    private java.util.List<org.example.protobuf.models.common.Car> car_ =
      java.util.Collections.emptyList();
    private void ensureCarIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        car_ = new java.util.ArrayList<org.example.protobuf.models.common.Car>(car_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.example.protobuf.models.common.Car, org.example.protobuf.models.common.Car.Builder, org.example.protobuf.models.common.CarOrBuilder> carBuilder_;

    /**
     * <code>repeated .common.Car car = 4;</code>
     */
    public java.util.List<org.example.protobuf.models.common.Car> getCarList() {
      if (carBuilder_ == null) {
        return java.util.Collections.unmodifiableList(car_);
      } else {
        return carBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .common.Car car = 4;</code>
     */
    public int getCarCount() {
      if (carBuilder_ == null) {
        return car_.size();
      } else {
        return carBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .common.Car car = 4;</code>
     */
    public org.example.protobuf.models.common.Car getCar(int index) {
      if (carBuilder_ == null) {
        return car_.get(index);
      } else {
        return carBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .common.Car car = 4;</code>
     */
    public Builder setCar(
        int index, org.example.protobuf.models.common.Car value) {
      if (carBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCarIsMutable();
        car_.set(index, value);
        onChanged();
      } else {
        carBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .common.Car car = 4;</code>
     */
    public Builder setCar(
        int index, org.example.protobuf.models.common.Car.Builder builderForValue) {
      if (carBuilder_ == null) {
        ensureCarIsMutable();
        car_.set(index, builderForValue.build());
        onChanged();
      } else {
        carBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .common.Car car = 4;</code>
     */
    public Builder addCar(org.example.protobuf.models.common.Car value) {
      if (carBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCarIsMutable();
        car_.add(value);
        onChanged();
      } else {
        carBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .common.Car car = 4;</code>
     */
    public Builder addCar(
        int index, org.example.protobuf.models.common.Car value) {
      if (carBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCarIsMutable();
        car_.add(index, value);
        onChanged();
      } else {
        carBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .common.Car car = 4;</code>
     */
    public Builder addCar(
        org.example.protobuf.models.common.Car.Builder builderForValue) {
      if (carBuilder_ == null) {
        ensureCarIsMutable();
        car_.add(builderForValue.build());
        onChanged();
      } else {
        carBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .common.Car car = 4;</code>
     */
    public Builder addCar(
        int index, org.example.protobuf.models.common.Car.Builder builderForValue) {
      if (carBuilder_ == null) {
        ensureCarIsMutable();
        car_.add(index, builderForValue.build());
        onChanged();
      } else {
        carBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .common.Car car = 4;</code>
     */
    public Builder addAllCar(
        java.lang.Iterable<? extends org.example.protobuf.models.common.Car> values) {
      if (carBuilder_ == null) {
        ensureCarIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, car_);
        onChanged();
      } else {
        carBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .common.Car car = 4;</code>
     */
    public Builder clearCar() {
      if (carBuilder_ == null) {
        car_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        carBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .common.Car car = 4;</code>
     */
    public Builder removeCar(int index) {
      if (carBuilder_ == null) {
        ensureCarIsMutable();
        car_.remove(index);
        onChanged();
      } else {
        carBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .common.Car car = 4;</code>
     */
    public org.example.protobuf.models.common.Car.Builder getCarBuilder(
        int index) {
      return getCarFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .common.Car car = 4;</code>
     */
    public org.example.protobuf.models.common.CarOrBuilder getCarOrBuilder(
        int index) {
      if (carBuilder_ == null) {
        return car_.get(index);  } else {
        return carBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .common.Car car = 4;</code>
     */
    public java.util.List<? extends org.example.protobuf.models.common.CarOrBuilder> 
         getCarOrBuilderList() {
      if (carBuilder_ != null) {
        return carBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(car_);
      }
    }
    /**
     * <code>repeated .common.Car car = 4;</code>
     */
    public org.example.protobuf.models.common.Car.Builder addCarBuilder() {
      return getCarFieldBuilder().addBuilder(
          org.example.protobuf.models.common.Car.getDefaultInstance());
    }
    /**
     * <code>repeated .common.Car car = 4;</code>
     */
    public org.example.protobuf.models.common.Car.Builder addCarBuilder(
        int index) {
      return getCarFieldBuilder().addBuilder(
          index, org.example.protobuf.models.common.Car.getDefaultInstance());
    }
    /**
     * <code>repeated .common.Car car = 4;</code>
     */
    public java.util.List<org.example.protobuf.models.common.Car.Builder> 
         getCarBuilderList() {
      return getCarFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.example.protobuf.models.common.Car, org.example.protobuf.models.common.Car.Builder, org.example.protobuf.models.common.CarOrBuilder> 
        getCarFieldBuilder() {
      if (carBuilder_ == null) {
        carBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.example.protobuf.models.common.Car, org.example.protobuf.models.common.Car.Builder, org.example.protobuf.models.common.CarOrBuilder>(
                car_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        car_ = null;
      }
      return carBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Person)
  }

  // @@protoc_insertion_point(class_scope:Person)
  private static final org.example.protobuf.models.person.Person DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.protobuf.models.person.Person();
  }

  public static org.example.protobuf.models.person.Person getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Person>
      PARSER = new com.google.protobuf.AbstractParser<Person>() {
    @java.lang.Override
    public Person parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Person> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Person> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.protobuf.models.person.Person getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

