// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dates.proto

package org.example.protobuf.models.dates;

public final class DatesOuterClass {
  private DatesOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Dates_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Dates_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013dates.proto\"\026\n\005Dates\022\r\n\005birth\030\001 \001(\tB%\n" +
      "!org.example.protobuf.models.datesP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Dates_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Dates_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Dates_descriptor,
        new java.lang.String[] { "Birth", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
