// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dates.proto

package org.example.protobuf.models.dates;

public interface DatesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Dates)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string birth = 1;</code>
   * @return The birth.
   */
  java.lang.String getBirth();
  /**
   * <code>string birth = 1;</code>
   * @return The bytes for birth.
   */
  com.google.protobuf.ByteString
      getBirthBytes();
}
