// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dealer.proto

package org.example.protobuf.models.dealer;

public interface DealerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Dealer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;int64, .common.Car&gt; model = 1;</code>
   */
  int getModelCount();
  /**
   * <code>map&lt;int64, .common.Car&gt; model = 1;</code>
   */
  boolean containsModel(
      long key);
  /**
   * Use {@link #getModelMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Long, org.example.protobuf.models.common.Car>
  getModel();
  /**
   * <code>map&lt;int64, .common.Car&gt; model = 1;</code>
   */
  java.util.Map<java.lang.Long, org.example.protobuf.models.common.Car>
  getModelMap();
  /**
   * <code>map&lt;int64, .common.Car&gt; model = 1;</code>
   */

  /* nullable */
org.example.protobuf.models.common.Car getModelOrDefault(
      long key,
      /* nullable */
org.example.protobuf.models.common.Car defaultValue);
  /**
   * <code>map&lt;int64, .common.Car&gt; model = 1;</code>
   */

  org.example.protobuf.models.common.Car getModelOrThrow(
      long key);

  /**
   * <code>.common.Address address = 2;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>.common.Address address = 2;</code>
   * @return The address.
   */
  org.example.protobuf.models.common.Address getAddress();
  /**
   * <code>.common.Address address = 2;</code>
   */
  org.example.protobuf.models.common.AddressOrBuilder getAddressOrBuilder();
}
