// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dealer.proto

package org.example.protobuf.models.dealer;

public final class DealerOuterClass {
  private DealerOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Dealer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Dealer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Dealer_ModelEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Dealer_ModelEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014dealer.proto\032\024common/address.proto\032\020co" +
      "mmon/car.proto\"\210\001\n\006Dealer\022!\n\005model\030\001 \003(\013" +
      "2\022.Dealer.ModelEntry\022 \n\007address\030\002 \001(\0132\017." +
      "common.Address\0329\n\nModelEntry\022\013\n\003key\030\001 \001(" +
      "\003\022\032\n\005value\030\002 \001(\0132\013.common.Car:\0028\001B&\n\"org" +
      ".example.protobuf.models.dealerP\001b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.example.protobuf.models.common.AddressOuterClass.getDescriptor(),
          org.example.protobuf.models.common.CarOuterClass.getDescriptor(),
        });
    internal_static_Dealer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Dealer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Dealer_descriptor,
        new java.lang.String[] { "Model", "Address", });
    internal_static_Dealer_ModelEntry_descriptor =
      internal_static_Dealer_descriptor.getNestedTypes().get(0);
    internal_static_Dealer_ModelEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Dealer_ModelEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    org.example.protobuf.models.common.AddressOuterClass.getDescriptor();
    org.example.protobuf.models.common.CarOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
